### ISSUE TITLE
R1 resistor on Logitech_Pedal_Shield_Pro_Micro

### ISSUE THREAD

**Issue by lkvapil** [dmadison/Sim-Racing-Shields#2]
Hi!

just wondering why did you add a R1-10k resistor between 5-9pin on the DB9 connector (6-1 in the schematics)
Is there any other purpose of the resistor ?
![Snímek obrazovky 2023-09-01 v 12 28 28](https://github.com/dmadison/Sim-Racing-Shields/assets/16653942/c8f933bc-32f1-464e-b58b-6a91bc04f480)

Doing some research, did a teardown of the pedals and G29 base and seems, that on the DB9 connector pins 6 and 9 does need 3V3 voltage.
Also on the DB9 on the pedals cable are pins 6 and 9 connected..

Thank you

Best regards
Lukas

**Comment by dmadison** [comment]
Hi Lukas! That's a great question.

You can see the results of my own breakdown of the pinout [in the library documentation](https://dmadison.github.io/Sim-Racing-Arduino/docs/logitech_pedals.html).

As you've discovered, pins 6 and 9 are connected internally in the pedal connector. The shield provides power on pin 9, which means pin 6 also gets powered whenever the pedals are connected. This allows pin 6 to be used as a detection pin, where the resistor (R1) acts as a pull-down. When the pedals are disconnected the pin is low (through the resistor), when the pedals are connected the pin is high (connected to VCC through pin 9).

If you don't care about the detection feature you can omit the resistor and the detection pin in the object constructor. The microcontroller will just read/send junk values when the pedals are disconnected.

>on the DB9 connector pins 6 and 9 does need 3V3 voltage.

On my pedals at least the only connections inside the pedals are to the pedal potentiometers themselves, which can use any high level voltage below the limit of the potentiometer. 5V works fine.

>between 5-9pin on the DB9 connector (6-1 in the schematics)

Careful that you're using the correct DB9 connector! The footprint is flipped depending on the gender. The connector pinout on the shield should match the schematic 1:1.

**Comment by dmadison** [comment]
I haven't heard back from you so I'm considering this solved. Feel free to reopen if you have more questions.
